version: "3.9"

services: 
  watchtower:
    image: v2tec/watchtower
    container_name: leveling-education-framework-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  app:
    image: spark156/leveling-education-framework:latest
    container_name: leveling-education-framework
    build:
      context: app
      target: runner
    networks:
      - caddy
    labels:
      caddy: ${HOSTS}
      caddy.reverse_proxy: "{{upstreams 3000}}"
    
networks:
  caddy:
    external: true

